# ================================================ Register User ================================================ #

POST http://localhost:3003/user/signup
Content-Type: application/json

{
    "name": "Lance Vance",
    "email": "lance@email.com",
    "password": "lance1234"
}

###
POST http://localhost:3003/user/signup
Content-Type: application/json

{
    "name": "Howard Hamlin",
    "email": "howard@email.com",
    "password": "howard1234"
}

# ================================================ Making Login ================================================ #

###
POST http://localhost:3003/user/login
Content-Type: application/json

{
    "email": "lance@email.com",
    "password": "lance1234"
}

###
POST http://localhost:3003/user/login
Content-Type: application/json

{
    "email": "howard@email.com",
    "password": "howard1234"
}

# ================================================ Get Own Profile ================================================ #

###
GET  http://localhost:3003/user/profile
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImJjZjczOWEyLTY2NzQtNDBiNC05MTFjLTdiMTYyMmE3YmVhMCIsImlhdCI6MTY3NjczNzgyOSwiZXhwIjoxNjc2NzQxNDI5fQ.YR_Nqc6UaKr459N0kzAtgxBKe8vzmywQeU3terwvDOg

# ================================================ Get Other User ================================================ #

###
GET  http://localhost:3003/user/bcf739a2-6674-40b4-911c-7b1622a7bea0
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImFhOWI1MTBlLTNmNGQtNGJjNy1iYjMxLTE2NDM5NDdiZGRjNSIsImlhdCI6MTY3NjY4NDU2NCwiZXhwIjoxNjc2Njg4MTY0fQ.TlMvf6jk50bIg5NSaTeZgSeShyzR40W-9Hov1LVNPfY

# ================================================ Create Recipe ================================================ #

###
POST http://localhost:3003/recipe/create
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImJjZjczOWEyLTY2NzQtNDBiNC05MTFjLTdiMTYyMmE3YmVhMCIsImlhdCI6MTY3NjczNzgyOSwiZXhwIjoxNjc2NzQxNDI5fQ.YR_Nqc6UaKr459N0kzAtgxBKe8vzmywQeU3terwvDOg

{
    "title": "Massa de pizza rápida e fácil",
    "description": "Em um liquidificador, coloque ovo, leite, manteiga, sal, açúcar, farinha e bata até ficar homogêneo."
}

###
POST http://localhost:3003/recipe/create
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImJjZjczOWEyLTY2NzQtNDBiNC05MTFjLTdiMTYyMmE3YmVhMCIsImlhdCI6MTY3NjczNzgyOSwiZXhwIjoxNjc2NzQxNDI5fQ.YR_Nqc6UaKr459N0kzAtgxBKe8vzmywQeU3terwvDOg

{
    "title": "Pão de alho",
    "description": "Pão e alho"
}

# ================================================ Get Recipe ================================================ #

###
GET  http://localhost:3003/recipe/716b8587-144a-4e0e-9a71-6390702196cd
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImJjZjczOWEyLTY2NzQtNDBiNC05MTFjLTdiMTYyMmE3YmVhMCIsImlhdCI6MTY3Njc1MzMxMiwiZXhwIjoxNjc2NzU2OTEyfQ.XT6Uaqai4xAqGarIRofZHFkmaydeCU6yALxwCyH-meM
