# ================================================ Register Users ================================================ #

POST http://localhost:3003/user/signup
Content-Type: application/json

{
    "name": "Lance Vance",
    "email": "lance@email.com",
    "password": "lance1234"
}

###
POST http://localhost:3003/user/signup
Content-Type: application/json

{
    "name": "Howard Hamlin",
    "email": "howard@email.com",
    "password": "howard1234"
}

# ================================================ Making Logins ================================================ #

###
POST http://localhost:3003/user/login
Content-Type: application/json

{
    "email": "lance@email.com",
    "password": "lance1234"
}

###
POST http://localhost:3003/user/login
Content-Type: application/json

{
    "email": "howard@email.com",
    "password": "howard1234"
}

# ================================================ Get Own Profile ================================================ #

###
GET  http://localhost:3003/user/profile
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImJjZjczOWEyLTY2NzQtNDBiNC05MTFjLTdiMTYyMmE3YmVhMCIsImlhdCI6MTY3NjY4NDYzOCwiZXhwIjoxNjc2Njg4MjM4fQ.taiU3JO886ciutm9W2R--s2YagmyQvrB89JoRXHYJM8

# ================================================ Get Other User ================================================ #

###
GET  http://localhost:3003/user/bcf739a2-6674-40b4-911c-7b1622a7bea0
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImFhOWI1MTBlLTNmNGQtNGJjNy1iYjMxLTE2NDM5NDdiZGRjNSIsImlhdCI6MTY3NjY4NDU2NCwiZXhwIjoxNjc2Njg4MTY0fQ.TlMvf6jk50bIg5NSaTeZgSeShyzR40W-9Hov1LVNPfY